import Link from 'next/link';
import { PRESET_LIST } from '@mailmotion/presets';
import gallery from '@/generated/gallery.json';
import { REPO_URL, SiteFooter, SiteHeader } from '@/components/SiteChrome';

type GalleryEntry = { name: string; bestFor: string; html: string; chars: number };
const items = gallery as Record<string, GalleryEntry>;

export default function Home() {
  return (
    <>
      <SiteHeader />
      <main className="wrap">
        <section className="hero">
          <p className="eyebrow">Open source · self-hosted · no tracking</p>
          <h1>
            Animated email signatures that <em>actually render.</em>
          </h1>
          <p className="lede">
            Pick a design, add your details, and get a signature with an animated avatar and a
            hand-inked mark that works in Gmail, Outlook and Apple Mail, on desktop and on your
            phone. Everything runs in your browser.
          </p>
          <div className="cta-row">
            <Link href="/studio/" className="btn primary">
              Build my signature
            </Link>
            <a href={REPO_URL} className="btn">
              Star on GitHub
            </a>
          </div>
          <p className="fineprint">
            Every design keeps frame 1 complete (classic Outlook shows only that frame), stays under
            10,000 characters, and ships GIFs of 300 KB or less at 12 fps or less.
          </p>
        </section>

        <section className="section" id="designs">
          <h2>Six designs, all real output</h2>
          <p className="lede">
            These are generated by the same renderer and serializer the builder uses: table-based
            HTML with hosted GIFs. Every part can be customized or remixed.
          </p>
          <div className="gallery">
            {PRESET_LIST.map((p) => {
              const g = items[p.id];
              if (!g) return null;
              return (
                <article className="g-card" key={p.id}>
                  <div className="g-head">
                    <h3>{g.name}</h3>
                    <span>{g.bestFor}</span>
                  </div>
                  {/* Trusted: generated at build time by our own serializer from fixed sample data. */}
                  <div className="g-stage" dangerouslySetInnerHTML={{ __html: g.html }} />
                  <div className="g-foot">
                    {p.layout} layout · {p.avatarAnimation} avatar · frame 1:{' '}
                    {p.frame1.toLowerCase()} · {g.chars.toLocaleString('en-US')} chars
                  </div>
                </article>
              );
            })}
          </div>
        </section>

        <section className="section">
          <h2>Built for the inbox, not the browser</h2>
          <p className="lede">
            Email clients are hostile places. MailMotion works within their rules instead of hoping
            for the best.
          </p>
          <div className="features">
            <div className="feature">
              <h3>It renders for real</h3>
              <p>
                Table layouts, inline styles, hosted GIFs and PNG icons. No SVG, no{' '}
                <code>&lt;style&gt;</code>, no data URIs that Gmail strips.
              </p>
            </div>
            <div className="feature">
              <h3>Private by default</h3>
              <p>
                No tracking pixels, no read receipts, no accounts. Photos are processed in your
                browser and metadata is stripped.
              </p>
            </div>
            <div className="feature">
              <h3>Open source</h3>
              <p>
                Self-host it with Docker, use the CLI in CI, or fork a design. The engine is MIT,
                the apps are AGPL.
              </p>
            </div>
            <div className="feature">
              <h3>Security built in</h3>
              <p>
                Everything is HTML-escaped, links are https-only, uploads are re-validated and the
                builder ships a strict CSP.
              </p>
            </div>
          </div>
        </section>

        <section className="section">
          <h2>From idea to installed in a few minutes</h2>
          <div className="steps">
            <div className="step">
              <h3>Design</h3>
              <p>
                Pick a design, enter your name and photo, and tweak colours, fonts, socials and your
                signature mark.
              </p>
            </div>
            <div className="step">
              <h3>Host the images</h3>
              <p>
                Gmail needs public image URLs. Publish free to your own GitHub Pages in one click,
                or use your own storage.
              </p>
            </div>
            <div className="step">
              <h3>Install</h3>
              <p>
                Copy the signature into Gmail or Outlook, or use the Apple Mail file and the
                send-to-phone page.
              </p>
            </div>
          </div>
        </section>

        <section className="section">
          <h2>Two ways to host the images</h2>
          <div className="table-wrap">
            <table className="plain">
              <thead>
                <tr>
                  <th />
                  <th>Path A: your storage</th>
                  <th>Path B: GitHub Pages</th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <td>For</td>
                  <td>Technical users and teams</td>
                  <td>Everyone else</td>
                </tr>
                <tr>
                  <td>How</td>
                  <td>
                    <code>docker compose up</code> with disk, S3, R2 or MinIO
                  </td>
                  <td>Sign in with GitHub, click Publish</td>
                </tr>
                <tr>
                  <td>Image URL</td>
                  <td>
                    <code>https://img.yourdomain.com/&lt;hash&gt;.gif</code>
                  </td>
                  <td>
                    <code>https://&lt;you&gt;.github.io/mailmotion-signatures/…</code>
                  </td>
                </tr>
                <tr>
                  <td>Cost</td>
                  <td>Your own storage (often free)</td>
                  <td>Free</td>
                </tr>
              </tbody>
            </table>
          </div>
          <p className="fineprint" style={{ marginTop: 12 }}>
            Prefer neither? Download a ZIP, host the files anywhere, and MailMotion regenerates the
            HTML with your base URL.
          </p>
        </section>
      </main>
      <SiteFooter />
    </>
  );
}
